// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Restaurant.Models;

public partial class Article
{
    public Article(string name, decimal price, string description, sbyte active, int idType)
    {
        this.Name = name;
        this.Price = price; 
        this.Description = description;
        this.Active = active;
        this.IdType = idType;
    }
    public Article(int id,string name, decimal price, string description, sbyte active, int idType)
    {
        this.Id = id;
        this.Name = name;
        this.Price = price;
        this.Description = description;
        this.Active = active;
        this.IdType = idType;
    }
    public Article() { }

    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public sbyte Active { get; set; }

    public int IdType { get; set; }

    public virtual ArticleType IdTypeNavigation { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
    public override bool Equals(object obj)
    {
        return Equals(obj as Article);
    }

    public bool Equals(Article other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;

        return Id == other.Id;
    }
}