// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Restaurant.Models;

public partial class Employee
{
    public string Jmb { get; set; }

    public string Name { get; set; }

    public string Prezime { get; set; }

    public string Address { get; set; }

    public int Salary { get; set; }

    public sbyte IsManager { get; set; }

    public string Telephone { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Theme { get; set; }

    public string Language { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}