// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Restaurant.Models;

public partial class Reservation
{
    public DateTime DateAndTime { get; set; }

    public string PersonName { get; set; }

    public int IdReservation { get; set; }
}