// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Restaurant.Models;

public partial class Restaurant
{
    public string Name { get; set; }

    public string Address { get; set; }

    public string Telephone { get; set; }
}